dataset_name: thumos
train_split: ['validation']
val_split: ['test']
dataset: {
  #json_file: /data/ljh/actionformer/thumos/annotations/thumos14.json,
  json_file: /data1/mcy/dataset/actionformer-data/thumos/annotations/thumos14_classnoise_N0.1boundarynoise_N0.3.json,
  feat_folder: /data1/mcy/dataset/actionformer-data/thumos/i3d_features,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 20,
  input_dim: 2048,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
# 元学习/data1/mcy/dataset/actionformer-data/thumos/annotations/thumos14.json
dataset_meta: {
  json_file: /data1/mcy/dataset/actionformer-data/thumos/annotations/thumos14_gold.json,
  feat_folder: /data1/mcy/dataset/actionformer-data/thumos/i3d_features,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 20,
  input_dim: 2048,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 2304,
  default_fps: null,
  downsample_rate: 1,
  force_upsampling: False,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 19,
}

#opt: {
#  type: "AdamW",
#  learning_rate: 0.01,
#  epochs: 30,
#  weight_decay: 0.0001,
#}
opt: {
  type: "SGD",
#  type: "AdamW",
  learning_rate: 0.01,
  epochs: 30,
  weight_decay: 0.005,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  #center_sample: none,
  center_sample_radius: 1.5,
  loss_weight: 1.0,
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: /data1/mcy/code/AAAI2025/actionformer_meta_denoise/ckpt
#output_folder: /data/ljh/actionformer/ckpt/
